### ISSUE TITLE
Test on OPENSEA

### ISSUE THREAD

**Issue by soujiang** [masudrehman/goblin-lol-smart_contract#1]
Hello, I am using your smart contract to do some tests on OPENSEA, could you tell me what I have to put in placeholderURI:? and in _baseTokenURI: can "ipfs://hash/" be added or is it added in another way? What happens is that with other contracts the metadata is not displayed in OPENSEA.

**Comment by masudrehman** [comment]
You have to add the metadata link in it..
In both of them

**Comment by soujiang** [comment]
thank you very much, the contract works perfectly
