### ISSUE TITLE
OPENSEA changes in the payment of fees for creators of NFTs collections

### ISSUE THREAD

**Issue by soujiang** [masudrehman/goblin-lol-smart_contract#2]
Hello, have you heard about the OPENSEA changes in the payment of fees for creators of NFTs collections?

https://opensea.io/blog/announcements/on-creator-fees/

and its implementation?

https://github.com/ProjectOpenSea/operator-filter-registry

**Comment by masudrehman** [comment]
Not related to my repository

**Comment by soujiang** [comment]
I asked the question, in case you were going to make changes to the smart contract to make it compatible with the new OPENSEA regulations, because in December all those who do not comply with the regulations will not be able to receive royalties for their collections From November 8, all Implemented smart contracts cannot receive royalties unless they meet certain standards. While smart contracts that are already receiving royalties will stop receiving them. Your smart contract is up and running, but it no longer allows you to add royalties through OPENSEA unless you include a few more lines of code. C:

**Comment by masudrehman** [comment]
i don't know about it. didn't checked it.
